name: Run checks for PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get Node.js version from package.json
        id: get_node_version
        uses: keita-hino/get-node-version-from-volta@main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.get_node_version.outputs.nodeVersion }}"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint and check code
        run: pnpm run check

      - name: Build project
        run: pnpm build
        env:
          NODE_ENV: production
